name = "serial-number-app-v2"
client_id = "80f6bda70f68d9493dd520a62584696e"
application_url = "https://serial-number-app-v2.onrender.com"
embedded = true

[access_scopes]
scopes = "read_orders, write_orders, read_draft_orders, read_customers, write_app_proxy, read_app_proxy, read_products, read_fulfillments, read_assigned_fulfillment_orders, read_metaobjects, write_metaobjects, write_metaobject_definitions, read_metaobject_definitions, write_order_edits, read_order_edits, write_merchant_managed_fulfillment_orders, read_merchant_managed_fulfillment_orders, write_assigned_fulfillment_orders"

[auth]
redirect_urls = [
  "https://serial-number-app-v2.onrender.com/auth/callback",
  "https://serial-number-app-v2.onrender.com/auth/shopify/callback",
  "https://serial-number-app-v2.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"
